# Generated by Django 3.0.5 on 2020-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodydetails',
            name='email',
        ),
        migrations.AddField(
            model_name='bodydetails',
            name='bid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
