# Generated by Django 3.0.5 on 2020-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensic', '0002_auto_20200727_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodydetails',
            name='bid',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
    ]
