# Generated by Django 3.0.5 on 2020-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bid', models.CharField(default='', max_length=40, unique=True)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('ldh', models.CharField(max_length=40)),
                ('ast', models.CharField(max_length=40)),
                ('triglycerides', models.CharField(max_length=40)),
                ('phlevel', models.CharField(max_length=40)),
                ('pmi', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'doctorreport',
            },
        ),
    ]
