# Generated by Django 3.0.5 on 2020-07-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctorreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctorreport',
            new_name='doctorreportmodel',
        ),
    ]
